version: '3.8'

networks:
  ozon-network:
    name: ozon-network

volumes:
  redis-data:
    driver: local

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - ozon-network

  celery:
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "app.my_celery", "worker", "--loglevel=info"]
    restart: always
    networks:
      - ozon-network

  celery-beat:
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "app.my_celery", "beat", "--loglevel=info"]
    restart: always
    networks:
      - ozon-network