version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "app.my_celery", "worker", "--loglevel=info"]
    restart: always

  celery-beat:
    build: ./app
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["celery", "-A", "app.my_celery", "beat", "--loglevel=info"]
    restart: always